### ISSUE TITLE
Add copy link button to popup when in room

### ISSUE THREAD

**Issue by ElementalMP4** [Elementalmp4/NetflixParty#1]
When in a room, allow users to open up the chrome popup to see a copy room URL button

**Comment by ozgurozbek** [comment]
Don't you already have this at [453794a](https://github.com/Elementalmp4/NetflixParty/commit/453794a149f5ec5421e91220b1eff7f5cc08c1c8)

**Comment by ElementalMP4** [comment]
> Don't you already have this at [453794a](https://github.com/Elementalmp4/NetflixParty/commit/453794a149f5ec5421e91220b1eff7f5cc08c1c8)

That is correct, I can close this issue now thank you
