### ISSUE TITLE
Running the service on own server

### ISSUE THREAD

**Issue by abdurrezzak** [Elementalmp4/NetflixParty#4]
Hello, first of all, amazing work! 

I am not too familiar with Java project structure. When I run 
`javac -NetflixParty.java `

I get an error as the following  
`NetflixParty.java:5: error: package org.springframework.boot does not exist
import org.springframework.boot.SpringApplication;
                               ^
NetflixParty.java:6: error: package org.springframework.boot.autoconfigure does not exist
import org.springframework.boot.autoconfigure.SpringBootApplication;
                                             ^
NetflixParty.java:7: error: package org.springframework.context.annotation does not exist
import org.springframework.context.annotation.Bean;
                                             ^
NetflixParty.java:9: error: package main.java.de.voidtech.netflixparty.service does not exist
import main.java.de.voidtech.netflixparty.service.ConfigService;
                                                 ^
NetflixParty.java:11: error: cannot find symbol
@SpringBootApplication
 ^
  symbol: class SpringBootApplication
NetflixParty.java:14: error: cannot find symbol
        private static ConfigService configService;
                       ^
  symbol:   class ConfigService
  location: class NetflixParty
NetflixParty.java:38: error: cannot find symbol
        public ConfigService getConfigService() {
               ^
  symbol:   class ConfigService
  location: class NetflixParty
NetflixParty.java:37: error: cannot find symbol
        @Bean
         ^
  symbol:   class Bean
  location: class NetflixParty
NetflixParty.java:17: error: cannot find symbol
                SpringApplication springApp = new SpringApplication(NetflixParty.class);
                ^
  symbol:   class SpringApplication
  location: class NetflixParty
NetflixParty.java:17: error: cannot find symbol
                SpringApplication springApp = new SpringApplication(NetflixParty.class);
                                                  ^
  symbol:   class SpringApplication
  location: class NetflixParty
NetflixParty.java:20: error: cannot find symbol
                configService = new ConfigService();
                                    ^
  symbol:   class ConfigService
  location: class NetflixParty
11 errors` 

What would be the next step to solve this? We are using Ubuntu 20.04 on GCP.

**Comment by ElementalMP4** [comment]
Hey there!
Thanks for taking an interest in this project! To get this running, you'll want to compile the project using maven (if you have a Java IDE such as eclipse or intelliJ this comes bundled and I can show you how to set up a build config for it)

I'd recommend doing a `git fetch` of this repo on your Ubuntu server, then inside the project directory run `mvn clean package` to compile it into a jar. You can run that jar with `java -jar target/original-NetflixParty-0.0.1.jar` (the name might be wrong, but you'll find the jar in the target directory once maven has finished compiling)

If you don't have maven on your server you can install it with `apt install maven`

I hope that helps!

**Comment by abdurrezzak** [comment]
Thanks for your prompt response! I was able to install maven and build the project. 

I also created a _config.properties_ file inside the **target** folder. Inside that file, I copied the following lines:

```
http.port=6969 //Set the HTTP/WebSocket port
cache.TextIsEnabled=true //Choose whether text files should be cached
cache.BinaryIsEnabled=true //Choose whether binary files should be cached
```

However, I got the following error. 

```
####    ###    #########  ###########  #########  ####        ####   ###     ###
#####   ###    #########  ###########  #########  ####        ####    ###   ### 
######  ###    ###            ###      ###        ####        ####     ### ###  
######  ###    ###            ###      ###        ####        ####      #####   
####### ###    ########       ###      ########   ####        ####      ####    
#### ######    ###            ###      ###        ####        ####     ######   
####  #####    ###            ###      ###        ####        ####    ########  
####   ####    #########      ###      ###        ##########  ####   ####  #### 
####   ####    #########      ###      ###        ##########  ###   ####    ####

2023-03-10 15:35:47.281  INFO 1053196 --- [           main] m.j.d.v.netflixparty.NetflixParty        : Starting NetflixParty v0.0.1-SNAPSHOT using Java 11.0.18 on son-durak with PID 1053196 (/home/movie_project_tinder/SineBuddyParty/NetflixParty-main/target/original-NetflixParty-0.0.1-SNAPSHOT.jar started by movie_project_tinder in /home/movie_project_tinder/SineBuddyParty/NetflixParty-main/target)
2023-03-10 15:35:47.297  INFO 1053196 --- [           main] m.j.d.v.netflixparty.NetflixParty        : No active profile set, falling back to default profiles: default
2023-03-10 15:35:49.038  INFO 1053196 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-03-10 15:35:49.078  INFO 1053196 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 15 ms. Found 0 JPA repository interfaces.
2023-03-10 15:35:49.870  WARN 1053196 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servletWebServerFactoryCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryAutoConfiguration.class]: Unsatisfied dependency expressed through method 'servletWebServerFactoryCustomizer' parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'server-org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'server.port' to java.lang.Integer
2023-03-10 15:35:49.882  INFO 1053196 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-03-10 15:35:49.902 ERROR 1053196 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'server.port' to java.lang.Integer:

    Property: server.port
    Value: 6969 //Set the HTTP/WebSocket port
    Origin: "server.port" from property source "defaultProperties"
    Reason: failed to convert java.lang.String to java.lang.Integer

Action:

Update your application's configuration

```

**Comment by ElementalMP4** [comment]
You can fix this by changing the comments slightly:

```
#Set the HTTP/WebSocket port
http.port=6969
#Choose whether text files should be cached
cache.TextIsEnabled=true
#Choose whether binary files should be cached
cache.BinaryIsEnabled=true
```
comments in `.properties` files should start with a # and they need to be on their own line

**Comment by abdurrezzak** [comment]
It seems to work now, I have a problem with wss and https calls I guess but that might be because I use the external IP address of the VM instance. Thanks a lot!

**Comment by abdurrezzak** [comment]
I worked with this project for a while and I bought a domain that is IP proxied via nginx. An SSL certificate is also handled for it. The problem is when a room is created with the create-room js, the messaging panel does not load. Also, pausing, playing and synchrony is not working. The browser console shows following: 
`netflix-party-interface.js:836 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Either the 'unsafe-inline' keyword, a hash ('sha256-9QLhOtqMa+nIIT6npy6TxrrS7myG7booMm/xOmnxURs='), or a nonce ('nonce-...') is required to enable inline execution.

embedInPage @ netflix-party-interface.js:836
80218201:1 Access to XMLHttpRequest at 'https://assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico' from origin 'https://www.netflix.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico:1          Failed to load resource: net::ERR_FAILED
tp_libraries_min.js:1 Teleparty: Injecting Libraries
netflix_content_bundled.js:6 Message Controller
netflix_content_bundled.js:6 Video Event Listener
netflix_content_bundled.js:6 injecting replace script
VM429:2 Loaded Replace Script
netflix_content_bundled.js:6 Teleparty Browse Loaded 1002469828
netflix_content_bundled.js:6 Setting Page COntrols
netflix_content_bundled.js:6 Chat forwarder
netflix_content_bundled.js:6 Video forwarder
netflix_content_bundled.js:6 Netflix Content Script
netflix_content_bundled.js:6 Initialized content script
netflix_content_bundled.js:6 Got background script
netflix_injected_bundled.js:426 Loaded TP Netflix Injected
www3.doubleclick.net/:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM427:293 [NetflixParty] Gateway Connected
VM427:293 [NetflixParty] Attempting to add listeners...
VM427:293 [NetflixParty] Player undefined! Waiting before next listener attempt
80218201:1 Access to XMLHttpRequest at 'https://assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico' from origin 'https://www.netflix.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico:1          Failed to load resource: net::ERR_FAILED
VM427:293 [NetflixParty] Attempting to add listeners...
VM427:293 [NetflixParty] Player undefined! Waiting before next listener attempt
VM427:293 [NetflixParty] Attempting to add listeners...
VM427:293 [NetflixParty] Player undefined! Waiting before next listener attempt
2netflix_content_bundled.js:6 Got video
VM427:293 [NetflixParty] Attempting to add listeners...
VM427:293 [NetflixParty] Adding listeners!
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:293 [NetflixParty] Paused
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:293 [NetflixParty] Ignoring pause event
VM427:293 [NetflixParty] Playing at 00:00:24
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:670 Uncaught TypeError: Cannot read properties of undefined (reading 'time')
    at Globals.GATEWAY.onmessage (<anonymous>:670:41)
Globals.GATEWAY.onmessage @ VM427:670
VM427:293 [NetflixParty] Paused
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:293 [NetflixParty] Ignoring pause event
VM427:293 [NetflixParty] Playing at 00:00:26
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:670 Uncaught TypeError: Cannot read properties of undefined (reading 'time')
    at Globals.GATEWAY.onmessage (<anonymous>:670:41)
VM427:293 [NetflixParty] Paused
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:293 [NetflixParty] Ignoring pause event
VM427:293 [NetflixParty] Playing at 00:00:27
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:670 Uncaught TypeError: Cannot read properties of undefined (reading 'time')
    at Globals.GATEWAY.onmessage (<anonymous>:670:41)
VM427:293 [NetflixParty] Paused
VM427:293 [NetflixParty] Sent Object
VM427:293 [NetflixParty] Received Object
VM427:293 [NetflixParty] Ignoring pause event
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND`

Note that I am running the server on a GCP VM. Do you have an idea what the problem might be? @ElementalMP4 for visibility.
